# Generated by Django 4.1 on 2023-02-04 19:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Additive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("make", models.CharField(max_length=50)),
                ("package", models.CharField(max_length=20)),
                (
                    "concentration",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "concunit",
                    models.CharField(choices=[("M", "M"), ("%", "%")], max_length=2),
                ),
                (
                    "wv_vv",
                    models.CharField(
                        choices=[("W/V", "W/V"), ("V/V", "V/V")], max_length=3
                    ),
                ),
                ("makedate", models.DateField(null=True)),
                ("expdate", models.DateField(null=True)),
                ("a_combiname", models.CharField(max_length=20, unique=True)),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "addedby",
                    models.ForeignKey(
                        db_column="a_addedby",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="a_addedby",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Buffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("make", models.CharField(max_length=50)),
                ("package", models.CharField(max_length=20)),
                ("concentration", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "concunit",
                    models.CharField(
                        choices=[("mg", "mg"), ("ml", "ml"), ("%", "%")],
                        default="mg",
                        max_length=7,
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                ("makedate", models.DateField(null=True)),
                ("expdate", models.DateField(null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                ("b_combiname", models.CharField(max_length=20, unique=True)),
                (
                    "addedby",
                    models.ForeignKey(
                        db_column="b_addedby",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="b_addedby",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cell_row",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                (
                    "cell_column",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "ressol_volume",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "protein_volume",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("startdate", models.DateField()),
                (
                    "cellstatus",
                    models.CharField(
                        choices=[
                            ("InObservation", "InObservation"),
                            ("Stopped", "Stopped"),
                            ("Characterisation", "Characterisation"),
                        ],
                        default="InObservation",
                        max_length=16,
                    ),
                ),
                ("cell_combiname", models.CharField(max_length=20, unique=True)),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "addedby",
                    models.ForeignKey(
                        db_column="c_addedby",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="c_addedby",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Precipitant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("make", models.CharField(max_length=50)),
                ("package", models.CharField(max_length=20)),
                (
                    "concentration",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "concunit",
                    models.CharField(choices=[("M", "M"), ("%", "%")], max_length=2),
                ),
                (
                    "wv_vv",
                    models.CharField(
                        choices=[("W/V", "W/V"), ("V/V", "V/V")], max_length=3
                    ),
                ),
                ("makedate", models.DateField(null=True)),
                ("expdate", models.DateField(null=True)),
                ("p_combiname", models.CharField(max_length=20, unique=True)),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "addedby",
                    models.ForeignKey(
                        db_column="p_addedby",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="p_addedby",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservoirsolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "b_volume",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "p_volume",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "a1_volume",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "a2_volume",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("rs_combinedname", models.CharField(max_length=20, unique=True)),
                ("remark", models.TextField(null=True)),
                ("makedate", models.DateField(default=django.utils.timezone.now)),
                (
                    "addedby",
                    models.ForeignKey(
                        db_column="rs_addedby",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rs_addedby",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "additive1",
                    models.ForeignKey(
                        db_column="additive1",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="additive1",
                        to="explogger.additive",
                        to_field="a_combiname",
                    ),
                ),
                (
                    "additive2",
                    models.ForeignKey(
                        blank=True,
                        db_column="additive2",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="additive2",
                        to="explogger.additive",
                        to_field="a_combiname",
                    ),
                ),
                (
                    "buffer",
                    models.ForeignKey(
                        db_column="buffer",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="buffer",
                        to="explogger.buffer",
                        to_field="b_combiname",
                    ),
                ),
                (
                    "precipitant",
                    models.ForeignKey(
                        db_column="precip",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="precip",
                        to="explogger.precipitant",
                        to_field="p_combiname",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("puri_method", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Company", "Company"),
                            ("Patient", "Patient"),
                            ("Volume", "Volume"),
                            ("Leaf", "Leaf"),
                        ],
                        default="Company",
                        max_length=20,
                    ),
                ),
                (
                    "concentration",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "concunit",
                    models.CharField(
                        choices=[("M", "M"), ("%", "%")], default="M", max_length=2
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "addedby",
                    models.ForeignKey(
                        db_column="pr_addedby",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pr_addedby",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_name", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Closed", "Closed")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "addedby",
                    models.ForeignKey(
                        db_column="pl_addedby",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pl_addedby",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "base_protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="explogger.protein",
                    ),
                ),
                (
                    "base_rsolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="explogger.reservoirsolution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("combiname", models.CharField(blank=True, max_length=20, null=True)),
                ("observ_date", models.DateField()),
                ("observ_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "crystal_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "crystal_size",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/cells/%Y/%m/%d/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("InObservation", "InObservation"),
                            ("Stopped", "Stopped"),
                            ("Characterisation", "Characterisation"),
                        ],
                        default="InObservation",
                        max_length=16,
                    ),
                ),
                ("nextdate", models.DateField()),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "addedby",
                    models.ForeignKey(
                        db_column="o_addedby",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="o_addedby",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "cellname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="explogger.cell",
                    ),
                ),
                (
                    "platename",
                    models.ForeignKey(
                        db_column="platename",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platename",
                        to="explogger.plate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cell",
            name="plate",
            field=models.ForeignKey(
                db_column="plate",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plate",
                to="explogger.plate",
            ),
        ),
        migrations.AddField(
            model_name="cell",
            name="protein",
            field=models.ForeignKey(
                db_column="protein",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="protein",
                to="explogger.protein",
            ),
        ),
        migrations.AddField(
            model_name="cell",
            name="reservoirsolution",
            field=models.ForeignKey(
                db_column="rs",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="rs",
                to="explogger.reservoirsolution",
            ),
        ),
    ]
